matrix:
  include:
    - language: python
      python: 
        - 3.5
      services:
        - mysql
      before_install:
        - sudo mkdir -p /services/logs/
        - sudo chown -R travis /services/logs/
        - cd monitor_api2/
        - mysql -e 'CREATE DATABASE IF NOT EXISTS test_monitor;'
        - mysql -u root -e "CREATE USER 'dba'@'localhost' IDENTIFIED BY '123456';"
        - mysql -e "GRANT ALL PRIVILEGES ON monitor.* TO 'dba'@'localhost';"
        - mysql -e 'FLUSH PRIVILEGES;'
      env:
        -DJANGO=2.13 DB=mysql
      install: 
        - pip install -r requirements.txt
      script:
        - DJANGO_SETTINGS_MODULE='web.travis_settings' ./manage.py test


