matrix:
  include:
    - language: python
      python: 
        - 3.5
      services:
        - mysql
      before_install:
        - cd monitor_api2/
      env:
        -DJANGO=2.13 DB=mysql
      install: 
        - pip install -r requirements.txt
      script:
        - python manage.py test

