matrix:
  include:
  - language: python
    python:
    - 3.5
    services:
    - mysql
    before_install:
    - openssl aes-256-cbc -K $encrypted_8833d0168ab5_key -iv $encrypted_8833d0168ab5_iv
      -in deploy_key.enc -out ./deploy_key -d
    - eval "$(ssh-agent -s)"
    - chmod 600 ./deploy_key
    - echo -e "Host evoupsight.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - ssh-add ./deploy_key
    - ssh -i ./deploy_key -p6000 root@evoupsight.com /shell/deploy.sh
    - sudo mkdir -p /services/logs/
    - sudo chown -R travis /services/logs/
    - cd monitor_api2/
    - mysql -e "CREATE USER 'dba'@'localhost' IDENTIFIED BY '123456';"
    - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'dba'@'localhost';"
    - mysql -e 'FLUSH PRIVILEGES;'
    env: "-DJANGO=2.13 DB=mysql"
    install:
    - pip install -r requirements.txt
    script:
    - DJANGO_SETTINGS_MODULE='web.travis_settings' ./manage.py test
