matrix:
  include:
    - language: python
      python: 
        - 3.5
      services:
        - mysql
      before_install:
        - sudo mkdir -p /services/logs/
        - sudo chown -R travis /services/logs/
        - cd monitor_api2/
      env:
        -DJANGO=2.13 DB=mysql
      install: 
        - pip install -r requirements.txt
      script:
        - DJANGO_SETTINGS_MODULE='web.travis_settings' ./manage.py test


