version: '3'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dba
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: monitor
    volumes:
      - ./files/init.sql:/data/application/init.sql
    security_opt:
      - seccomp:unconfined

  api: # django App
    container_name: monitor-api2
    build: ./files/images/
    command: python3 ./monitor_api2/manage.py runserver 0.0.0.0:8000 --insecure
    volumes:
      - .:/code
    ports:
      - "8000:8000" # Expose API port
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  frontend: # Nginx Server For Frontend App
    container_name: monitor-ui2
    image: nginx
    volumes:
      - ./monitor_ui2:/usr/share/nginx/html
      - ./files/default.conf:/etc/nginx/conf.d/default.conf # proxy api 8000 to 80 port
    ports:
      - "80:80" # Forward site to localhost:80



