version: '2.2'

services:
  db:
    container_name: monitor-pass-db
    image: mysql:5.7
    #command: --default-authentication-plugin=mysql_native_password --init-file /code/files/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dba
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: monitor
      DJANGO_SETTINGS_MODULE: web.travis_settings
    volumes:
      - .:/code
      - monitor_db_data_volume:/var/lib/mysql
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306" # same for localhost dev
    healthcheck:
      test: "/usr/bin/mysql --user=dba --password=123456 --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  api: # django App
    container_name: monitor-api2
    build:
      context: ./files/images/
      dockerfile: Dockerfile
      #args:
        #- http_proxy=http://192.168.2.197:8124
        #- https_proxy=http://192.168.2.197:8124
    image: monitor-pass-api:2.0
    command: python3 ./monitor_api2/manage.py runserver 0.0.0.0:8000 --insecure
    restart: always
    volumes:
      - .:/code
      - /services/logs/monitor-api2:/services/logs/
    ports:
      - "8000:8000" # Expose API port
    depends_on:
      db:
        condition: service_healthy
    links:
    - db:mydb

  adminer:
    container_name: monitor-pass-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  frontend: # Nginx Server For Frontend App
    container_name: monitor-ui2
    image: nginx
    restart: always
    volumes:
      - ./monitor_ui2:/usr/share/nginx/html
      - ./files/default.conf:/etc/nginx/conf.d/default.conf # proxy api 8000 to 80 port
    ports:
      - "80:80" # Forward site to localhost:80
    depends_on:
      - api


volumes:
    monitor_db_data_volume:
