package com.evoupsight.monitorpass.datacollector.dao.mapper;

import com.evoupsight.monitorpass.datacollector.dao.model.DataCollector;
import com.evoupsight.monitorpass.datacollector.dao.model.DataCollectorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DataCollectorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_collector
     *
     * @mbg.generated Thu Aug 15 23:49:51 CST 2019
     */
    long countByExample(DataCollectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_collector
     *
     * @mbg.generated Thu Aug 15 23:49:51 CST 2019
     */
    int deleteByExample(DataCollectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_collector
     *
     * @mbg.generated Thu Aug 15 23:49:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_collector
     *
     * @mbg.generated Thu Aug 15 23:49:51 CST 2019
     */
    int insert(DataCollector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_collector
     *
     * @mbg.generated Thu Aug 15 23:49:51 CST 2019
     */
    int insertSelective(DataCollector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_collector
     *
     * @mbg.generated Thu Aug 15 23:49:51 CST 2019
     */
    List<DataCollector> selectByExample(DataCollectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_collector
     *
     * @mbg.generated Thu Aug 15 23:49:51 CST 2019
     */
    DataCollector selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_collector
     *
     * @mbg.generated Thu Aug 15 23:49:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") DataCollector record, @Param("example") DataCollectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_collector
     *
     * @mbg.generated Thu Aug 15 23:49:51 CST 2019
     */
    int updateByExample(@Param("record") DataCollector record, @Param("example") DataCollectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_collector
     *
     * @mbg.generated Thu Aug 15 23:49:51 CST 2019
     */
    int updateByPrimaryKeySelective(DataCollector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_collector
     *
     * @mbg.generated Thu Aug 15 23:49:51 CST 2019
     */
    int updateByPrimaryKey(DataCollector record);
}