package com.evoupsight.monitorpass.datacollector.dao.mapper;

import com.evoupsight.monitorpass.datacollector.dao.model.RelationTemplateServerGroup;
import com.evoupsight.monitorpass.datacollector.dao.model.RelationTemplateServerGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelationTemplateServerGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_template_server_group
     *
     * @mbg.generated
     */
    long countByExample(RelationTemplateServerGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_template_server_group
     *
     * @mbg.generated
     */
    int deleteByExample(RelationTemplateServerGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_template_server_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_template_server_group
     *
     * @mbg.generated
     */
    int insert(RelationTemplateServerGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_template_server_group
     *
     * @mbg.generated
     */
    int insertSelective(RelationTemplateServerGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_template_server_group
     *
     * @mbg.generated
     */
    List<RelationTemplateServerGroup> selectByExample(RelationTemplateServerGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_template_server_group
     *
     * @mbg.generated
     */
    RelationTemplateServerGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_template_server_group
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RelationTemplateServerGroup record, @Param("example") RelationTemplateServerGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_template_server_group
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RelationTemplateServerGroup record, @Param("example") RelationTemplateServerGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_template_server_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RelationTemplateServerGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_template_server_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RelationTemplateServerGroup record);
}