# Generated by Django 2.1.3 on 2019-02-23 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type_id', models.IntegerField(choices=[(1, '服务器'), (2, '交换机'), (3, '防火墙')], default=1)),
                ('device_status_id', models.IntegerField(choices=[(1, '上架'), (2, '在线'), (3, '离线'), (4, '下架')], default=1)),
                ('cabinet_num', models.CharField(blank=True, max_length=30, null=True, verbose_name='机柜号')),
                ('cabinet_order', models.CharField(blank=True, max_length=30, null=True, verbose_name='机柜中序号')),
                ('latest_date', models.DateField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'asset',
                'verbose_name_plural': '资产表',
            },
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='业务线')),
            ],
            options={
                'db_table': 'business_unit',
                'verbose_name_plural': '业务线表',
            },
        ),
        migrations.CreateModel(
            name='DataCollector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='数据收集器名')),
                ('ip', models.CharField(max_length=20, verbose_name='IP地址')),
                ('port', models.IntegerField(verbose_name='端口号')),
                ('desc', models.CharField(max_length=50, null=True, verbose_name='描述')),
            ],
            options={
                'db_table': 'data_collector',
                'verbose_name_plural': '数据收集器表',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=200, verbose_name='监控事件')),
                ('date', models.DateTimeField(verbose_name='发生时间')),
            ],
            options={
                'db_table': 'event',
                'verbose_name_plural': '监控事件表',
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='机房')),
                ('floor', models.IntegerField(default=1, verbose_name='楼层')),
            ],
            options={
                'db_table': 'idc',
                'verbose_name_plural': '机房表',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='服务器主机名')),
                ('ip', models.CharField(max_length=20, verbose_name='IP地址')),
                ('status', models.IntegerField(choices=[(0, '宕机'), (1, '在线'), (2, '不监控')], default=0)),
            ],
            options={
                'db_table': 'server',
                'verbose_name_plural': '服务器表',
            },
        ),
        migrations.CreateModel(
            name='ServerGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='服务器组名')),
                ('desc', models.CharField(max_length=512, null=True, verbose_name='描述')),
                ('alarm_type', models.IntegerField(choices=[(0, '不接收'), (1, '普通报警'), (2, '严重报警'), (3, '素有报警')], default=0, verbose_name='告警类型')),
            ],
            options={
                'db_table': 'server_group',
                'verbose_name_plural': '服务器组名',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='标签')),
            ],
            options={
                'db_table': 'tag',
                'verbose_name_plural': '标签表',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='用户组名')),
            ],
            options={
                'db_table': 'user_group',
                'verbose_name_plural': '用户组表',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('telephone', models.CharField(max_length=32, verbose_name='座机')),
                ('mobile', models.IntegerField(verbose_name='手机')),
                ('user', models.OneToOneField(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
                'verbose_name_plural': '用户信息表',
            },
        ),
        migrations.AddField(
            model_name='server',
            name='server_group',
            field=models.ManyToManyField(db_table='r_server_server_group', to='monitor_web.ServerGroup'),
        ),
        migrations.AddField(
            model_name='event',
            name='host_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor_web.Server'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c', to='monitor_web.UserGroup', verbose_name='业务联系人'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m', to='monitor_web.UserGroup', verbose_name='系统管理员'),
        ),
        migrations.AddField(
            model_name='asset',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor_web.BusinessUnit', verbose_name='属于的业务线'),
        ),
        migrations.AddField(
            model_name='asset',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor_web.IDC', verbose_name='IDC机房'),
        ),
        migrations.AddField(
            model_name='asset',
            name='tag',
            field=models.ManyToManyField(db_table='r_asset_tag', to='monitor_web.Tag'),
        ),
    ]
