# Generated by Django 2.1.3 on 2019-03-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='floor',
            field=models.IntegerField(blank=True, default=1, verbose_name='楼层'),
        ),
    ]
