# Generated by Django 2.1.9 on 2019-09-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='monitor_item',
        ),
    ]
