package com.evoupsight.monitorpass.server.dao.mapper;

import com.evoupsight.monitorpass.server.dao.model.Trigger;
import com.evoupsight.monitorpass.server.dao.model.TriggerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TriggerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trigger
     *
     * @mbg.generated
     */
    long countByExample(TriggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trigger
     *
     * @mbg.generated
     */
    int deleteByExample(TriggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trigger
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trigger
     *
     * @mbg.generated
     */
    int insert(Trigger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trigger
     *
     * @mbg.generated
     */
    int insertSelective(Trigger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trigger
     *
     * @mbg.generated
     */
    List<Trigger> selectByExampleSelective(@Param("example") TriggerExample example, @Param("selective") Trigger.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trigger
     *
     * @mbg.generated
     */
    List<Trigger> selectByExample(TriggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trigger
     *
     * @mbg.generated
     */
    Trigger selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") Trigger.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trigger
     *
     * @mbg.generated
     */
    Trigger selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trigger
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Trigger record, @Param("example") TriggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trigger
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Trigger record, @Param("example") TriggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trigger
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Trigger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trigger
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Trigger record);
}