package com.evoupsight.monitorpass.server.dao.model;

import java.util.ArrayList;
import java.util.Arrays;

public class Function {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.parameter
     *
     * @mbg.generated
     */
    private String parameter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.item_id
     *
     * @mbg.generated
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.trigger_id
     *
     * @mbg.generated
     */
    private Long triggerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.id
     *
     * @return the value of function.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.id
     *
     * @param id the value for function.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.name
     *
     * @return the value of function.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.name
     *
     * @param name the value for function.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.parameter
     *
     * @return the value of function.parameter
     *
     * @mbg.generated
     */
    public String getParameter() {
        return parameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.parameter
     *
     * @param parameter the value for function.parameter
     *
     * @mbg.generated
     */
    public void setParameter(String parameter) {
        this.parameter = parameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.item_id
     *
     * @return the value of function.item_id
     *
     * @mbg.generated
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.item_id
     *
     * @param itemId the value for function.item_id
     *
     * @mbg.generated
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.trigger_id
     *
     * @return the value of function.trigger_id
     *
     * @mbg.generated
     */
    public Long getTriggerId() {
        return triggerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.trigger_id
     *
     * @param triggerId the value for function.trigger_id
     *
     * @mbg.generated
     */
    public void setTriggerId(Long triggerId) {
        this.triggerId = triggerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table function
     *
     * @mbg.generated
     */
    public static Function.Builder builder() {
        return new Function.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table function
     *
     * @mbg.generated
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table function
         *
         * @mbg.generated
         */
        private Function obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table function
         *
         * @mbg.generated
         */
        public Builder() {
            this.obj = new Function();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column function.id
         *
         * @param id the value for function.id
         *
         * @mbg.generated
         */
        public Builder id(Long id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column function.name
         *
         * @param name the value for function.name
         *
         * @mbg.generated
         */
        public Builder name(String name) {
            obj.setName(name);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column function.parameter
         *
         * @param parameter the value for function.parameter
         *
         * @mbg.generated
         */
        public Builder parameter(String parameter) {
            obj.setParameter(parameter);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column function.item_id
         *
         * @param itemId the value for function.item_id
         *
         * @mbg.generated
         */
        public Builder itemId(Integer itemId) {
            obj.setItemId(itemId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column function.trigger_id
         *
         * @param triggerId the value for function.trigger_id
         *
         * @mbg.generated
         */
        public Builder triggerId(Long triggerId) {
            obj.setTriggerId(triggerId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table function
         *
         * @mbg.generated
         */
        public Function build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table function
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "BIGINT", false),
        name("name", "name", "VARCHAR", true),
        parameter("parameter", "parameter", "VARCHAR", true),
        itemId("item_id", "itemId", "INTEGER", false),
        triggerId("trigger_id", "triggerId", "BIGINT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table function
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table function
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table function
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table function
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table function
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table function
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table function
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table function
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table function
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table function
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table function
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table function
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table function
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table function
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table function
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table function
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}