package com.evoupsight.monitorpass.server.dao.model;

import java.util.ArrayList;
import java.util.Arrays;

public class RelationTemplateServerGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_template_server_group.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_template_server_group.template_id
     *
     * @mbg.generated
     */
    private Long templateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_template_server_group.servergroup_id
     *
     * @mbg.generated
     */
    private Integer servergroupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_template_server_group.id
     *
     * @return the value of r_template_server_group.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_template_server_group.id
     *
     * @param id the value for r_template_server_group.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_template_server_group.template_id
     *
     * @return the value of r_template_server_group.template_id
     *
     * @mbg.generated
     */
    public Long getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_template_server_group.template_id
     *
     * @param templateId the value for r_template_server_group.template_id
     *
     * @mbg.generated
     */
    public void setTemplateId(Long templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_template_server_group.servergroup_id
     *
     * @return the value of r_template_server_group.servergroup_id
     *
     * @mbg.generated
     */
    public Integer getServergroupId() {
        return servergroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_template_server_group.servergroup_id
     *
     * @param servergroupId the value for r_template_server_group.servergroup_id
     *
     * @mbg.generated
     */
    public void setServergroupId(Integer servergroupId) {
        this.servergroupId = servergroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_template_server_group
     *
     * @mbg.generated
     */
    public static RelationTemplateServerGroup.Builder builder() {
        return new RelationTemplateServerGroup.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table r_template_server_group
     *
     * @mbg.generated
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table r_template_server_group
         *
         * @mbg.generated
         */
        private RelationTemplateServerGroup obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table r_template_server_group
         *
         * @mbg.generated
         */
        public Builder() {
            this.obj = new RelationTemplateServerGroup();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column r_template_server_group.id
         *
         * @param id the value for r_template_server_group.id
         *
         * @mbg.generated
         */
        public Builder id(Integer id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column r_template_server_group.template_id
         *
         * @param templateId the value for r_template_server_group.template_id
         *
         * @mbg.generated
         */
        public Builder templateId(Long templateId) {
            obj.setTemplateId(templateId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column r_template_server_group.servergroup_id
         *
         * @param servergroupId the value for r_template_server_group.servergroup_id
         *
         * @mbg.generated
         */
        public Builder servergroupId(Integer servergroupId) {
            obj.setServergroupId(servergroupId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table r_template_server_group
         *
         * @mbg.generated
         */
        public RelationTemplateServerGroup build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table r_template_server_group
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        templateId("template_id", "templateId", "BIGINT", false),
        servergroupId("servergroup_id", "servergroupId", "INTEGER", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table r_template_server_group
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table r_template_server_group
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table r_template_server_group
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table r_template_server_group
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table r_template_server_group
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table r_template_server_group
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table r_template_server_group
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table r_template_server_group
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table r_template_server_group
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table r_template_server_group
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table r_template_server_group
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table r_template_server_group
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table r_template_server_group
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table r_template_server_group
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table r_template_server_group
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table r_template_server_group
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}