package com.evoupsight.monitorpass.datacollector.dao.model;

public class DataCollector {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collector.id
     *
     * @mbg.generated Thu Aug 15 23:49:51 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collector.name
     *
     * @mbg.generated Thu Aug 15 23:49:51 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collector.ip
     *
     * @mbg.generated Thu Aug 15 23:49:51 CST 2019
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_collector.port
     *
     * @mbg.generated Thu Aug 15 23:49:51 CST 2019
     */
    private Integer port;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collector.id
     *
     * @return the value of data_collector.id
     *
     * @mbg.generated Thu Aug 15 23:49:51 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collector.id
     *
     * @param id the value for data_collector.id
     *
     * @mbg.generated Thu Aug 15 23:49:51 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collector.name
     *
     * @return the value of data_collector.name
     *
     * @mbg.generated Thu Aug 15 23:49:51 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collector.name
     *
     * @param name the value for data_collector.name
     *
     * @mbg.generated Thu Aug 15 23:49:51 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collector.ip
     *
     * @return the value of data_collector.ip
     *
     * @mbg.generated Thu Aug 15 23:49:51 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collector.ip
     *
     * @param ip the value for data_collector.ip
     *
     * @mbg.generated Thu Aug 15 23:49:51 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_collector.port
     *
     * @return the value of data_collector.port
     *
     * @mbg.generated Thu Aug 15 23:49:51 CST 2019
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_collector.port
     *
     * @param port the value for data_collector.port
     *
     * @mbg.generated Thu Aug 15 23:49:51 CST 2019
     */
    public void setPort(Integer port) {
        this.port = port;
    }
}