package com.evoupsight.monitorpass.datacollector.dao.model;

public class RelationServerServerGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_server_server_group.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_server_server_group.server_id
     *
     * @mbg.generated
     */
    private Integer serverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_server_server_group.servergroup_id
     *
     * @mbg.generated
     */
    private Integer servergroupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_server_server_group.id
     *
     * @return the value of r_server_server_group.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_server_server_group.id
     *
     * @param id the value for r_server_server_group.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_server_server_group.server_id
     *
     * @return the value of r_server_server_group.server_id
     *
     * @mbg.generated
     */
    public Integer getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_server_server_group.server_id
     *
     * @param serverId the value for r_server_server_group.server_id
     *
     * @mbg.generated
     */
    public void setServerId(Integer serverId) {
        this.serverId = serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_server_server_group.servergroup_id
     *
     * @return the value of r_server_server_group.servergroup_id
     *
     * @mbg.generated
     */
    public Integer getServergroupId() {
        return servergroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_server_server_group.servergroup_id
     *
     * @param servergroupId the value for r_server_server_group.servergroup_id
     *
     * @mbg.generated
     */
    public void setServergroupId(Integer servergroupId) {
        this.servergroupId = servergroupId;
    }
}