package com.evoupsight.monitorpass.datacollector.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ServerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table server
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table server
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table server
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server
     *
     * @mbg.generated
     */
    public ServerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table server
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table server
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`name` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`name` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andIpIsNull() {
            addCriterion("ip is null");
            return (Criteria) this;
        }

        public Criteria andIpIsNotNull() {
            addCriterion("ip is not null");
            return (Criteria) this;
        }

        public Criteria andIpEqualTo(String value) {
            addCriterion("ip =", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotEqualTo(String value) {
            addCriterion("ip <>", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThan(String value) {
            addCriterion("ip >", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThanOrEqualTo(String value) {
            addCriterion("ip >=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThan(String value) {
            addCriterion("ip <", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThanOrEqualTo(String value) {
            addCriterion("ip <=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLike(String value) {
            addCriterion("ip like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotLike(String value) {
            addCriterion("ip not like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpIn(List<String> values) {
            addCriterion("ip in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotIn(List<String> values) {
            addCriterion("ip not in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpBetween(String value1, String value2) {
            addCriterion("ip between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotBetween(String value1, String value2) {
            addCriterion("ip not between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andHostnameIsNull() {
            addCriterion("hostname is null");
            return (Criteria) this;
        }

        public Criteria andHostnameIsNotNull() {
            addCriterion("hostname is not null");
            return (Criteria) this;
        }

        public Criteria andHostnameEqualTo(String value) {
            addCriterion("hostname =", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameNotEqualTo(String value) {
            addCriterion("hostname <>", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameGreaterThan(String value) {
            addCriterion("hostname >", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameGreaterThanOrEqualTo(String value) {
            addCriterion("hostname >=", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameLessThan(String value) {
            addCriterion("hostname <", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameLessThanOrEqualTo(String value) {
            addCriterion("hostname <=", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameLike(String value) {
            addCriterion("hostname like", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameNotLike(String value) {
            addCriterion("hostname not like", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameIn(List<String> values) {
            addCriterion("hostname in", values, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameNotIn(List<String> values) {
            addCriterion("hostname not in", values, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameBetween(String value1, String value2) {
            addCriterion("hostname between", value1, value2, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameNotBetween(String value1, String value2) {
            addCriterion("hostname not between", value1, value2, "hostname");
            return (Criteria) this;
        }

        public Criteria andSnIsNull() {
            addCriterion("sn is null");
            return (Criteria) this;
        }

        public Criteria andSnIsNotNull() {
            addCriterion("sn is not null");
            return (Criteria) this;
        }

        public Criteria andSnEqualTo(String value) {
            addCriterion("sn =", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnNotEqualTo(String value) {
            addCriterion("sn <>", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnGreaterThan(String value) {
            addCriterion("sn >", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnGreaterThanOrEqualTo(String value) {
            addCriterion("sn >=", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnLessThan(String value) {
            addCriterion("sn <", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnLessThanOrEqualTo(String value) {
            addCriterion("sn <=", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnLike(String value) {
            addCriterion("sn like", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnNotLike(String value) {
            addCriterion("sn not like", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnIn(List<String> values) {
            addCriterion("sn in", values, "sn");
            return (Criteria) this;
        }

        public Criteria andSnNotIn(List<String> values) {
            addCriterion("sn not in", values, "sn");
            return (Criteria) this;
        }

        public Criteria andSnBetween(String value1, String value2) {
            addCriterion("sn between", value1, value2, "sn");
            return (Criteria) this;
        }

        public Criteria andSnNotBetween(String value1, String value2) {
            addCriterion("sn not between", value1, value2, "sn");
            return (Criteria) this;
        }

        public Criteria andManufacturerIsNull() {
            addCriterion("manufacturer is null");
            return (Criteria) this;
        }

        public Criteria andManufacturerIsNotNull() {
            addCriterion("manufacturer is not null");
            return (Criteria) this;
        }

        public Criteria andManufacturerEqualTo(String value) {
            addCriterion("manufacturer =", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotEqualTo(String value) {
            addCriterion("manufacturer <>", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerGreaterThan(String value) {
            addCriterion("manufacturer >", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerGreaterThanOrEqualTo(String value) {
            addCriterion("manufacturer >=", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerLessThan(String value) {
            addCriterion("manufacturer <", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerLessThanOrEqualTo(String value) {
            addCriterion("manufacturer <=", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerLike(String value) {
            addCriterion("manufacturer like", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotLike(String value) {
            addCriterion("manufacturer not like", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerIn(List<String> values) {
            addCriterion("manufacturer in", values, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotIn(List<String> values) {
            addCriterion("manufacturer not in", values, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerBetween(String value1, String value2) {
            addCriterion("manufacturer between", value1, value2, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotBetween(String value1, String value2) {
            addCriterion("manufacturer not between", value1, value2, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andModelIsNull() {
            addCriterion("model is null");
            return (Criteria) this;
        }

        public Criteria andModelIsNotNull() {
            addCriterion("model is not null");
            return (Criteria) this;
        }

        public Criteria andModelEqualTo(String value) {
            addCriterion("model =", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotEqualTo(String value) {
            addCriterion("model <>", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelGreaterThan(String value) {
            addCriterion("model >", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelGreaterThanOrEqualTo(String value) {
            addCriterion("model >=", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelLessThan(String value) {
            addCriterion("model <", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelLessThanOrEqualTo(String value) {
            addCriterion("model <=", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelLike(String value) {
            addCriterion("model like", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotLike(String value) {
            addCriterion("model not like", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelIn(List<String> values) {
            addCriterion("model in", values, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotIn(List<String> values) {
            addCriterion("model not in", values, "model");
            return (Criteria) this;
        }

        public Criteria andModelBetween(String value1, String value2) {
            addCriterion("model between", value1, value2, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotBetween(String value1, String value2) {
            addCriterion("model not between", value1, value2, "model");
            return (Criteria) this;
        }

        public Criteria andManageIpIsNull() {
            addCriterion("manage_ip is null");
            return (Criteria) this;
        }

        public Criteria andManageIpIsNotNull() {
            addCriterion("manage_ip is not null");
            return (Criteria) this;
        }

        public Criteria andManageIpEqualTo(String value) {
            addCriterion("manage_ip =", value, "manageIp");
            return (Criteria) this;
        }

        public Criteria andManageIpNotEqualTo(String value) {
            addCriterion("manage_ip <>", value, "manageIp");
            return (Criteria) this;
        }

        public Criteria andManageIpGreaterThan(String value) {
            addCriterion("manage_ip >", value, "manageIp");
            return (Criteria) this;
        }

        public Criteria andManageIpGreaterThanOrEqualTo(String value) {
            addCriterion("manage_ip >=", value, "manageIp");
            return (Criteria) this;
        }

        public Criteria andManageIpLessThan(String value) {
            addCriterion("manage_ip <", value, "manageIp");
            return (Criteria) this;
        }

        public Criteria andManageIpLessThanOrEqualTo(String value) {
            addCriterion("manage_ip <=", value, "manageIp");
            return (Criteria) this;
        }

        public Criteria andManageIpLike(String value) {
            addCriterion("manage_ip like", value, "manageIp");
            return (Criteria) this;
        }

        public Criteria andManageIpNotLike(String value) {
            addCriterion("manage_ip not like", value, "manageIp");
            return (Criteria) this;
        }

        public Criteria andManageIpIn(List<String> values) {
            addCriterion("manage_ip in", values, "manageIp");
            return (Criteria) this;
        }

        public Criteria andManageIpNotIn(List<String> values) {
            addCriterion("manage_ip not in", values, "manageIp");
            return (Criteria) this;
        }

        public Criteria andManageIpBetween(String value1, String value2) {
            addCriterion("manage_ip between", value1, value2, "manageIp");
            return (Criteria) this;
        }

        public Criteria andManageIpNotBetween(String value1, String value2) {
            addCriterion("manage_ip not between", value1, value2, "manageIp");
            return (Criteria) this;
        }

        public Criteria andOsPlatformIsNull() {
            addCriterion("os_platform is null");
            return (Criteria) this;
        }

        public Criteria andOsPlatformIsNotNull() {
            addCriterion("os_platform is not null");
            return (Criteria) this;
        }

        public Criteria andOsPlatformEqualTo(String value) {
            addCriterion("os_platform =", value, "osPlatform");
            return (Criteria) this;
        }

        public Criteria andOsPlatformNotEqualTo(String value) {
            addCriterion("os_platform <>", value, "osPlatform");
            return (Criteria) this;
        }

        public Criteria andOsPlatformGreaterThan(String value) {
            addCriterion("os_platform >", value, "osPlatform");
            return (Criteria) this;
        }

        public Criteria andOsPlatformGreaterThanOrEqualTo(String value) {
            addCriterion("os_platform >=", value, "osPlatform");
            return (Criteria) this;
        }

        public Criteria andOsPlatformLessThan(String value) {
            addCriterion("os_platform <", value, "osPlatform");
            return (Criteria) this;
        }

        public Criteria andOsPlatformLessThanOrEqualTo(String value) {
            addCriterion("os_platform <=", value, "osPlatform");
            return (Criteria) this;
        }

        public Criteria andOsPlatformLike(String value) {
            addCriterion("os_platform like", value, "osPlatform");
            return (Criteria) this;
        }

        public Criteria andOsPlatformNotLike(String value) {
            addCriterion("os_platform not like", value, "osPlatform");
            return (Criteria) this;
        }

        public Criteria andOsPlatformIn(List<String> values) {
            addCriterion("os_platform in", values, "osPlatform");
            return (Criteria) this;
        }

        public Criteria andOsPlatformNotIn(List<String> values) {
            addCriterion("os_platform not in", values, "osPlatform");
            return (Criteria) this;
        }

        public Criteria andOsPlatformBetween(String value1, String value2) {
            addCriterion("os_platform between", value1, value2, "osPlatform");
            return (Criteria) this;
        }

        public Criteria andOsPlatformNotBetween(String value1, String value2) {
            addCriterion("os_platform not between", value1, value2, "osPlatform");
            return (Criteria) this;
        }

        public Criteria andOsVersionIsNull() {
            addCriterion("os_version is null");
            return (Criteria) this;
        }

        public Criteria andOsVersionIsNotNull() {
            addCriterion("os_version is not null");
            return (Criteria) this;
        }

        public Criteria andOsVersionEqualTo(String value) {
            addCriterion("os_version =", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionNotEqualTo(String value) {
            addCriterion("os_version <>", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionGreaterThan(String value) {
            addCriterion("os_version >", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionGreaterThanOrEqualTo(String value) {
            addCriterion("os_version >=", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionLessThan(String value) {
            addCriterion("os_version <", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionLessThanOrEqualTo(String value) {
            addCriterion("os_version <=", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionLike(String value) {
            addCriterion("os_version like", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionNotLike(String value) {
            addCriterion("os_version not like", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionIn(List<String> values) {
            addCriterion("os_version in", values, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionNotIn(List<String> values) {
            addCriterion("os_version not in", values, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionBetween(String value1, String value2) {
            addCriterion("os_version between", value1, value2, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionNotBetween(String value1, String value2) {
            addCriterion("os_version not between", value1, value2, "osVersion");
            return (Criteria) this;
        }

        public Criteria andCpuCountIsNull() {
            addCriterion("cpu_count is null");
            return (Criteria) this;
        }

        public Criteria andCpuCountIsNotNull() {
            addCriterion("cpu_count is not null");
            return (Criteria) this;
        }

        public Criteria andCpuCountEqualTo(Integer value) {
            addCriterion("cpu_count =", value, "cpuCount");
            return (Criteria) this;
        }

        public Criteria andCpuCountNotEqualTo(Integer value) {
            addCriterion("cpu_count <>", value, "cpuCount");
            return (Criteria) this;
        }

        public Criteria andCpuCountGreaterThan(Integer value) {
            addCriterion("cpu_count >", value, "cpuCount");
            return (Criteria) this;
        }

        public Criteria andCpuCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("cpu_count >=", value, "cpuCount");
            return (Criteria) this;
        }

        public Criteria andCpuCountLessThan(Integer value) {
            addCriterion("cpu_count <", value, "cpuCount");
            return (Criteria) this;
        }

        public Criteria andCpuCountLessThanOrEqualTo(Integer value) {
            addCriterion("cpu_count <=", value, "cpuCount");
            return (Criteria) this;
        }

        public Criteria andCpuCountIn(List<Integer> values) {
            addCriterion("cpu_count in", values, "cpuCount");
            return (Criteria) this;
        }

        public Criteria andCpuCountNotIn(List<Integer> values) {
            addCriterion("cpu_count not in", values, "cpuCount");
            return (Criteria) this;
        }

        public Criteria andCpuCountBetween(Integer value1, Integer value2) {
            addCriterion("cpu_count between", value1, value2, "cpuCount");
            return (Criteria) this;
        }

        public Criteria andCpuCountNotBetween(Integer value1, Integer value2) {
            addCriterion("cpu_count not between", value1, value2, "cpuCount");
            return (Criteria) this;
        }

        public Criteria andCpuPhysicalCountIsNull() {
            addCriterion("cpu_physical_count is null");
            return (Criteria) this;
        }

        public Criteria andCpuPhysicalCountIsNotNull() {
            addCriterion("cpu_physical_count is not null");
            return (Criteria) this;
        }

        public Criteria andCpuPhysicalCountEqualTo(Integer value) {
            addCriterion("cpu_physical_count =", value, "cpuPhysicalCount");
            return (Criteria) this;
        }

        public Criteria andCpuPhysicalCountNotEqualTo(Integer value) {
            addCriterion("cpu_physical_count <>", value, "cpuPhysicalCount");
            return (Criteria) this;
        }

        public Criteria andCpuPhysicalCountGreaterThan(Integer value) {
            addCriterion("cpu_physical_count >", value, "cpuPhysicalCount");
            return (Criteria) this;
        }

        public Criteria andCpuPhysicalCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("cpu_physical_count >=", value, "cpuPhysicalCount");
            return (Criteria) this;
        }

        public Criteria andCpuPhysicalCountLessThan(Integer value) {
            addCriterion("cpu_physical_count <", value, "cpuPhysicalCount");
            return (Criteria) this;
        }

        public Criteria andCpuPhysicalCountLessThanOrEqualTo(Integer value) {
            addCriterion("cpu_physical_count <=", value, "cpuPhysicalCount");
            return (Criteria) this;
        }

        public Criteria andCpuPhysicalCountIn(List<Integer> values) {
            addCriterion("cpu_physical_count in", values, "cpuPhysicalCount");
            return (Criteria) this;
        }

        public Criteria andCpuPhysicalCountNotIn(List<Integer> values) {
            addCriterion("cpu_physical_count not in", values, "cpuPhysicalCount");
            return (Criteria) this;
        }

        public Criteria andCpuPhysicalCountBetween(Integer value1, Integer value2) {
            addCriterion("cpu_physical_count between", value1, value2, "cpuPhysicalCount");
            return (Criteria) this;
        }

        public Criteria andCpuPhysicalCountNotBetween(Integer value1, Integer value2) {
            addCriterion("cpu_physical_count not between", value1, value2, "cpuPhysicalCount");
            return (Criteria) this;
        }

        public Criteria andCpuModelIsNull() {
            addCriterion("cpu_model is null");
            return (Criteria) this;
        }

        public Criteria andCpuModelIsNotNull() {
            addCriterion("cpu_model is not null");
            return (Criteria) this;
        }

        public Criteria andCpuModelEqualTo(String value) {
            addCriterion("cpu_model =", value, "cpuModel");
            return (Criteria) this;
        }

        public Criteria andCpuModelNotEqualTo(String value) {
            addCriterion("cpu_model <>", value, "cpuModel");
            return (Criteria) this;
        }

        public Criteria andCpuModelGreaterThan(String value) {
            addCriterion("cpu_model >", value, "cpuModel");
            return (Criteria) this;
        }

        public Criteria andCpuModelGreaterThanOrEqualTo(String value) {
            addCriterion("cpu_model >=", value, "cpuModel");
            return (Criteria) this;
        }

        public Criteria andCpuModelLessThan(String value) {
            addCriterion("cpu_model <", value, "cpuModel");
            return (Criteria) this;
        }

        public Criteria andCpuModelLessThanOrEqualTo(String value) {
            addCriterion("cpu_model <=", value, "cpuModel");
            return (Criteria) this;
        }

        public Criteria andCpuModelLike(String value) {
            addCriterion("cpu_model like", value, "cpuModel");
            return (Criteria) this;
        }

        public Criteria andCpuModelNotLike(String value) {
            addCriterion("cpu_model not like", value, "cpuModel");
            return (Criteria) this;
        }

        public Criteria andCpuModelIn(List<String> values) {
            addCriterion("cpu_model in", values, "cpuModel");
            return (Criteria) this;
        }

        public Criteria andCpuModelNotIn(List<String> values) {
            addCriterion("cpu_model not in", values, "cpuModel");
            return (Criteria) this;
        }

        public Criteria andCpuModelBetween(String value1, String value2) {
            addCriterion("cpu_model between", value1, value2, "cpuModel");
            return (Criteria) this;
        }

        public Criteria andCpuModelNotBetween(String value1, String value2) {
            addCriterion("cpu_model not between", value1, value2, "cpuModel");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNull() {
            addCriterion("create_at is null");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNotNull() {
            addCriterion("create_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreateAtEqualTo(Date value) {
            addCriterion("create_at =", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotEqualTo(Date value) {
            addCriterion("create_at <>", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThan(Date value) {
            addCriterion("create_at >", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThanOrEqualTo(Date value) {
            addCriterion("create_at >=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThan(Date value) {
            addCriterion("create_at <", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThanOrEqualTo(Date value) {
            addCriterion("create_at <=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtIn(List<Date> values) {
            addCriterion("create_at in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotIn(List<Date> values) {
            addCriterion("create_at not in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtBetween(Date value1, Date value2) {
            addCriterion("create_at between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotBetween(Date value1, Date value2) {
            addCriterion("create_at not between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andLastOnlineIsNull() {
            addCriterion("last_online is null");
            return (Criteria) this;
        }

        public Criteria andLastOnlineIsNotNull() {
            addCriterion("last_online is not null");
            return (Criteria) this;
        }

        public Criteria andLastOnlineEqualTo(Date value) {
            addCriterion("last_online =", value, "lastOnline");
            return (Criteria) this;
        }

        public Criteria andLastOnlineNotEqualTo(Date value) {
            addCriterion("last_online <>", value, "lastOnline");
            return (Criteria) this;
        }

        public Criteria andLastOnlineGreaterThan(Date value) {
            addCriterion("last_online >", value, "lastOnline");
            return (Criteria) this;
        }

        public Criteria andLastOnlineGreaterThanOrEqualTo(Date value) {
            addCriterion("last_online >=", value, "lastOnline");
            return (Criteria) this;
        }

        public Criteria andLastOnlineLessThan(Date value) {
            addCriterion("last_online <", value, "lastOnline");
            return (Criteria) this;
        }

        public Criteria andLastOnlineLessThanOrEqualTo(Date value) {
            addCriterion("last_online <=", value, "lastOnline");
            return (Criteria) this;
        }

        public Criteria andLastOnlineIn(List<Date> values) {
            addCriterion("last_online in", values, "lastOnline");
            return (Criteria) this;
        }

        public Criteria andLastOnlineNotIn(List<Date> values) {
            addCriterion("last_online not in", values, "lastOnline");
            return (Criteria) this;
        }

        public Criteria andLastOnlineBetween(Date value1, Date value2) {
            addCriterion("last_online between", value1, value2, "lastOnline");
            return (Criteria) this;
        }

        public Criteria andLastOnlineNotBetween(Date value1, Date value2) {
            addCriterion("last_online not between", value1, value2, "lastOnline");
            return (Criteria) this;
        }

        public Criteria andAgentAddressIsNull() {
            addCriterion("agent_address is null");
            return (Criteria) this;
        }

        public Criteria andAgentAddressIsNotNull() {
            addCriterion("agent_address is not null");
            return (Criteria) this;
        }

        public Criteria andAgentAddressEqualTo(String value) {
            addCriterion("agent_address =", value, "agentAddress");
            return (Criteria) this;
        }

        public Criteria andAgentAddressNotEqualTo(String value) {
            addCriterion("agent_address <>", value, "agentAddress");
            return (Criteria) this;
        }

        public Criteria andAgentAddressGreaterThan(String value) {
            addCriterion("agent_address >", value, "agentAddress");
            return (Criteria) this;
        }

        public Criteria andAgentAddressGreaterThanOrEqualTo(String value) {
            addCriterion("agent_address >=", value, "agentAddress");
            return (Criteria) this;
        }

        public Criteria andAgentAddressLessThan(String value) {
            addCriterion("agent_address <", value, "agentAddress");
            return (Criteria) this;
        }

        public Criteria andAgentAddressLessThanOrEqualTo(String value) {
            addCriterion("agent_address <=", value, "agentAddress");
            return (Criteria) this;
        }

        public Criteria andAgentAddressLike(String value) {
            addCriterion("agent_address like", value, "agentAddress");
            return (Criteria) this;
        }

        public Criteria andAgentAddressNotLike(String value) {
            addCriterion("agent_address not like", value, "agentAddress");
            return (Criteria) this;
        }

        public Criteria andAgentAddressIn(List<String> values) {
            addCriterion("agent_address in", values, "agentAddress");
            return (Criteria) this;
        }

        public Criteria andAgentAddressNotIn(List<String> values) {
            addCriterion("agent_address not in", values, "agentAddress");
            return (Criteria) this;
        }

        public Criteria andAgentAddressBetween(String value1, String value2) {
            addCriterion("agent_address between", value1, value2, "agentAddress");
            return (Criteria) this;
        }

        public Criteria andAgentAddressNotBetween(String value1, String value2) {
            addCriterion("agent_address not between", value1, value2, "agentAddress");
            return (Criteria) this;
        }

        public Criteria andSshAddressIsNull() {
            addCriterion("ssh_address is null");
            return (Criteria) this;
        }

        public Criteria andSshAddressIsNotNull() {
            addCriterion("ssh_address is not null");
            return (Criteria) this;
        }

        public Criteria andSshAddressEqualTo(String value) {
            addCriterion("ssh_address =", value, "sshAddress");
            return (Criteria) this;
        }

        public Criteria andSshAddressNotEqualTo(String value) {
            addCriterion("ssh_address <>", value, "sshAddress");
            return (Criteria) this;
        }

        public Criteria andSshAddressGreaterThan(String value) {
            addCriterion("ssh_address >", value, "sshAddress");
            return (Criteria) this;
        }

        public Criteria andSshAddressGreaterThanOrEqualTo(String value) {
            addCriterion("ssh_address >=", value, "sshAddress");
            return (Criteria) this;
        }

        public Criteria andSshAddressLessThan(String value) {
            addCriterion("ssh_address <", value, "sshAddress");
            return (Criteria) this;
        }

        public Criteria andSshAddressLessThanOrEqualTo(String value) {
            addCriterion("ssh_address <=", value, "sshAddress");
            return (Criteria) this;
        }

        public Criteria andSshAddressLike(String value) {
            addCriterion("ssh_address like", value, "sshAddress");
            return (Criteria) this;
        }

        public Criteria andSshAddressNotLike(String value) {
            addCriterion("ssh_address not like", value, "sshAddress");
            return (Criteria) this;
        }

        public Criteria andSshAddressIn(List<String> values) {
            addCriterion("ssh_address in", values, "sshAddress");
            return (Criteria) this;
        }

        public Criteria andSshAddressNotIn(List<String> values) {
            addCriterion("ssh_address not in", values, "sshAddress");
            return (Criteria) this;
        }

        public Criteria andSshAddressBetween(String value1, String value2) {
            addCriterion("ssh_address between", value1, value2, "sshAddress");
            return (Criteria) this;
        }

        public Criteria andSshAddressNotBetween(String value1, String value2) {
            addCriterion("ssh_address not between", value1, value2, "sshAddress");
            return (Criteria) this;
        }

        public Criteria andJmxAddressIsNull() {
            addCriterion("jmx_address is null");
            return (Criteria) this;
        }

        public Criteria andJmxAddressIsNotNull() {
            addCriterion("jmx_address is not null");
            return (Criteria) this;
        }

        public Criteria andJmxAddressEqualTo(String value) {
            addCriterion("jmx_address =", value, "jmxAddress");
            return (Criteria) this;
        }

        public Criteria andJmxAddressNotEqualTo(String value) {
            addCriterion("jmx_address <>", value, "jmxAddress");
            return (Criteria) this;
        }

        public Criteria andJmxAddressGreaterThan(String value) {
            addCriterion("jmx_address >", value, "jmxAddress");
            return (Criteria) this;
        }

        public Criteria andJmxAddressGreaterThanOrEqualTo(String value) {
            addCriterion("jmx_address >=", value, "jmxAddress");
            return (Criteria) this;
        }

        public Criteria andJmxAddressLessThan(String value) {
            addCriterion("jmx_address <", value, "jmxAddress");
            return (Criteria) this;
        }

        public Criteria andJmxAddressLessThanOrEqualTo(String value) {
            addCriterion("jmx_address <=", value, "jmxAddress");
            return (Criteria) this;
        }

        public Criteria andJmxAddressLike(String value) {
            addCriterion("jmx_address like", value, "jmxAddress");
            return (Criteria) this;
        }

        public Criteria andJmxAddressNotLike(String value) {
            addCriterion("jmx_address not like", value, "jmxAddress");
            return (Criteria) this;
        }

        public Criteria andJmxAddressIn(List<String> values) {
            addCriterion("jmx_address in", values, "jmxAddress");
            return (Criteria) this;
        }

        public Criteria andJmxAddressNotIn(List<String> values) {
            addCriterion("jmx_address not in", values, "jmxAddress");
            return (Criteria) this;
        }

        public Criteria andJmxAddressBetween(String value1, String value2) {
            addCriterion("jmx_address between", value1, value2, "jmxAddress");
            return (Criteria) this;
        }

        public Criteria andJmxAddressNotBetween(String value1, String value2) {
            addCriterion("jmx_address not between", value1, value2, "jmxAddress");
            return (Criteria) this;
        }

        public Criteria andSnmpAddressIsNull() {
            addCriterion("snmp_address is null");
            return (Criteria) this;
        }

        public Criteria andSnmpAddressIsNotNull() {
            addCriterion("snmp_address is not null");
            return (Criteria) this;
        }

        public Criteria andSnmpAddressEqualTo(String value) {
            addCriterion("snmp_address =", value, "snmpAddress");
            return (Criteria) this;
        }

        public Criteria andSnmpAddressNotEqualTo(String value) {
            addCriterion("snmp_address <>", value, "snmpAddress");
            return (Criteria) this;
        }

        public Criteria andSnmpAddressGreaterThan(String value) {
            addCriterion("snmp_address >", value, "snmpAddress");
            return (Criteria) this;
        }

        public Criteria andSnmpAddressGreaterThanOrEqualTo(String value) {
            addCriterion("snmp_address >=", value, "snmpAddress");
            return (Criteria) this;
        }

        public Criteria andSnmpAddressLessThan(String value) {
            addCriterion("snmp_address <", value, "snmpAddress");
            return (Criteria) this;
        }

        public Criteria andSnmpAddressLessThanOrEqualTo(String value) {
            addCriterion("snmp_address <=", value, "snmpAddress");
            return (Criteria) this;
        }

        public Criteria andSnmpAddressLike(String value) {
            addCriterion("snmp_address like", value, "snmpAddress");
            return (Criteria) this;
        }

        public Criteria andSnmpAddressNotLike(String value) {
            addCriterion("snmp_address not like", value, "snmpAddress");
            return (Criteria) this;
        }

        public Criteria andSnmpAddressIn(List<String> values) {
            addCriterion("snmp_address in", values, "snmpAddress");
            return (Criteria) this;
        }

        public Criteria andSnmpAddressNotIn(List<String> values) {
            addCriterion("snmp_address not in", values, "snmpAddress");
            return (Criteria) this;
        }

        public Criteria andSnmpAddressBetween(String value1, String value2) {
            addCriterion("snmp_address between", value1, value2, "snmpAddress");
            return (Criteria) this;
        }

        public Criteria andSnmpAddressNotBetween(String value1, String value2) {
            addCriterion("snmp_address not between", value1, value2, "snmpAddress");
            return (Criteria) this;
        }

        public Criteria andConfigUpdatedIsNull() {
            addCriterion("config_updated is null");
            return (Criteria) this;
        }

        public Criteria andConfigUpdatedIsNotNull() {
            addCriterion("config_updated is not null");
            return (Criteria) this;
        }

        public Criteria andConfigUpdatedEqualTo(Boolean value) {
            addCriterion("config_updated =", value, "configUpdated");
            return (Criteria) this;
        }

        public Criteria andConfigUpdatedNotEqualTo(Boolean value) {
            addCriterion("config_updated <>", value, "configUpdated");
            return (Criteria) this;
        }

        public Criteria andConfigUpdatedGreaterThan(Boolean value) {
            addCriterion("config_updated >", value, "configUpdated");
            return (Criteria) this;
        }

        public Criteria andConfigUpdatedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("config_updated >=", value, "configUpdated");
            return (Criteria) this;
        }

        public Criteria andConfigUpdatedLessThan(Boolean value) {
            addCriterion("config_updated <", value, "configUpdated");
            return (Criteria) this;
        }

        public Criteria andConfigUpdatedLessThanOrEqualTo(Boolean value) {
            addCriterion("config_updated <=", value, "configUpdated");
            return (Criteria) this;
        }

        public Criteria andConfigUpdatedIn(List<Boolean> values) {
            addCriterion("config_updated in", values, "configUpdated");
            return (Criteria) this;
        }

        public Criteria andConfigUpdatedNotIn(List<Boolean> values) {
            addCriterion("config_updated not in", values, "configUpdated");
            return (Criteria) this;
        }

        public Criteria andConfigUpdatedBetween(Boolean value1, Boolean value2) {
            addCriterion("config_updated between", value1, value2, "configUpdated");
            return (Criteria) this;
        }

        public Criteria andConfigUpdatedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("config_updated not between", value1, value2, "configUpdated");
            return (Criteria) this;
        }

        public Criteria andAssetIdIsNull() {
            addCriterion("asset_id is null");
            return (Criteria) this;
        }

        public Criteria andAssetIdIsNotNull() {
            addCriterion("asset_id is not null");
            return (Criteria) this;
        }

        public Criteria andAssetIdEqualTo(Integer value) {
            addCriterion("asset_id =", value, "assetId");
            return (Criteria) this;
        }

        public Criteria andAssetIdNotEqualTo(Integer value) {
            addCriterion("asset_id <>", value, "assetId");
            return (Criteria) this;
        }

        public Criteria andAssetIdGreaterThan(Integer value) {
            addCriterion("asset_id >", value, "assetId");
            return (Criteria) this;
        }

        public Criteria andAssetIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("asset_id >=", value, "assetId");
            return (Criteria) this;
        }

        public Criteria andAssetIdLessThan(Integer value) {
            addCriterion("asset_id <", value, "assetId");
            return (Criteria) this;
        }

        public Criteria andAssetIdLessThanOrEqualTo(Integer value) {
            addCriterion("asset_id <=", value, "assetId");
            return (Criteria) this;
        }

        public Criteria andAssetIdIn(List<Integer> values) {
            addCriterion("asset_id in", values, "assetId");
            return (Criteria) this;
        }

        public Criteria andAssetIdNotIn(List<Integer> values) {
            addCriterion("asset_id not in", values, "assetId");
            return (Criteria) this;
        }

        public Criteria andAssetIdBetween(Integer value1, Integer value2) {
            addCriterion("asset_id between", value1, value2, "assetId");
            return (Criteria) this;
        }

        public Criteria andAssetIdNotBetween(Integer value1, Integer value2) {
            addCriterion("asset_id not between", value1, value2, "assetId");
            return (Criteria) this;
        }

        public Criteria andDataCollectorIdIsNull() {
            addCriterion("data_collector_id is null");
            return (Criteria) this;
        }

        public Criteria andDataCollectorIdIsNotNull() {
            addCriterion("data_collector_id is not null");
            return (Criteria) this;
        }

        public Criteria andDataCollectorIdEqualTo(Integer value) {
            addCriterion("data_collector_id =", value, "dataCollectorId");
            return (Criteria) this;
        }

        public Criteria andDataCollectorIdNotEqualTo(Integer value) {
            addCriterion("data_collector_id <>", value, "dataCollectorId");
            return (Criteria) this;
        }

        public Criteria andDataCollectorIdGreaterThan(Integer value) {
            addCriterion("data_collector_id >", value, "dataCollectorId");
            return (Criteria) this;
        }

        public Criteria andDataCollectorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("data_collector_id >=", value, "dataCollectorId");
            return (Criteria) this;
        }

        public Criteria andDataCollectorIdLessThan(Integer value) {
            addCriterion("data_collector_id <", value, "dataCollectorId");
            return (Criteria) this;
        }

        public Criteria andDataCollectorIdLessThanOrEqualTo(Integer value) {
            addCriterion("data_collector_id <=", value, "dataCollectorId");
            return (Criteria) this;
        }

        public Criteria andDataCollectorIdIn(List<Integer> values) {
            addCriterion("data_collector_id in", values, "dataCollectorId");
            return (Criteria) this;
        }

        public Criteria andDataCollectorIdNotIn(List<Integer> values) {
            addCriterion("data_collector_id not in", values, "dataCollectorId");
            return (Criteria) this;
        }

        public Criteria andDataCollectorIdBetween(Integer value1, Integer value2) {
            addCriterion("data_collector_id between", value1, value2, "dataCollectorId");
            return (Criteria) this;
        }

        public Criteria andDataCollectorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("data_collector_id not between", value1, value2, "dataCollectorId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table server
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table server
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}