package com.evoupsight.monitorpass.datacollector.dao.model;

import java.util.Date;

public class Server {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.hostname
     *
     * @mbg.generated
     */
    private String hostname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.sn
     *
     * @mbg.generated
     */
    private String sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.manufacturer
     *
     * @mbg.generated
     */
    private String manufacturer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.model
     *
     * @mbg.generated
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.manage_ip
     *
     * @mbg.generated
     */
    private String manageIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.os_platform
     *
     * @mbg.generated
     */
    private String osPlatform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.os_version
     *
     * @mbg.generated
     */
    private String osVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.cpu_count
     *
     * @mbg.generated
     */
    private Integer cpuCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.cpu_physical_count
     *
     * @mbg.generated
     */
    private Integer cpuPhysicalCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.cpu_model
     *
     * @mbg.generated
     */
    private String cpuModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.create_at
     *
     * @mbg.generated
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.last_online
     *
     * @mbg.generated
     */
    private Date lastOnline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.agent_address
     *
     * @mbg.generated
     */
    private String agentAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.ssh_address
     *
     * @mbg.generated
     */
    private String sshAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.jmx_address
     *
     * @mbg.generated
     */
    private String jmxAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.snmp_address
     *
     * @mbg.generated
     */
    private String snmpAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.config_updated
     *
     * @mbg.generated
     */
    private Boolean configUpdated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.asset_id
     *
     * @mbg.generated
     */
    private Integer assetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column server.data_collector_id
     *
     * @mbg.generated
     */
    private Integer dataCollectorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.id
     *
     * @return the value of server.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.id
     *
     * @param id the value for server.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.name
     *
     * @return the value of server.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.name
     *
     * @param name the value for server.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.ip
     *
     * @return the value of server.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.ip
     *
     * @param ip the value for server.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.status
     *
     * @return the value of server.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.status
     *
     * @param status the value for server.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.hostname
     *
     * @return the value of server.hostname
     *
     * @mbg.generated
     */
    public String getHostname() {
        return hostname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.hostname
     *
     * @param hostname the value for server.hostname
     *
     * @mbg.generated
     */
    public void setHostname(String hostname) {
        this.hostname = hostname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.sn
     *
     * @return the value of server.sn
     *
     * @mbg.generated
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.sn
     *
     * @param sn the value for server.sn
     *
     * @mbg.generated
     */
    public void setSn(String sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.manufacturer
     *
     * @return the value of server.manufacturer
     *
     * @mbg.generated
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.manufacturer
     *
     * @param manufacturer the value for server.manufacturer
     *
     * @mbg.generated
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.model
     *
     * @return the value of server.model
     *
     * @mbg.generated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.model
     *
     * @param model the value for server.model
     *
     * @mbg.generated
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.manage_ip
     *
     * @return the value of server.manage_ip
     *
     * @mbg.generated
     */
    public String getManageIp() {
        return manageIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.manage_ip
     *
     * @param manageIp the value for server.manage_ip
     *
     * @mbg.generated
     */
    public void setManageIp(String manageIp) {
        this.manageIp = manageIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.os_platform
     *
     * @return the value of server.os_platform
     *
     * @mbg.generated
     */
    public String getOsPlatform() {
        return osPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.os_platform
     *
     * @param osPlatform the value for server.os_platform
     *
     * @mbg.generated
     */
    public void setOsPlatform(String osPlatform) {
        this.osPlatform = osPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.os_version
     *
     * @return the value of server.os_version
     *
     * @mbg.generated
     */
    public String getOsVersion() {
        return osVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.os_version
     *
     * @param osVersion the value for server.os_version
     *
     * @mbg.generated
     */
    public void setOsVersion(String osVersion) {
        this.osVersion = osVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.cpu_count
     *
     * @return the value of server.cpu_count
     *
     * @mbg.generated
     */
    public Integer getCpuCount() {
        return cpuCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.cpu_count
     *
     * @param cpuCount the value for server.cpu_count
     *
     * @mbg.generated
     */
    public void setCpuCount(Integer cpuCount) {
        this.cpuCount = cpuCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.cpu_physical_count
     *
     * @return the value of server.cpu_physical_count
     *
     * @mbg.generated
     */
    public Integer getCpuPhysicalCount() {
        return cpuPhysicalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.cpu_physical_count
     *
     * @param cpuPhysicalCount the value for server.cpu_physical_count
     *
     * @mbg.generated
     */
    public void setCpuPhysicalCount(Integer cpuPhysicalCount) {
        this.cpuPhysicalCount = cpuPhysicalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.cpu_model
     *
     * @return the value of server.cpu_model
     *
     * @mbg.generated
     */
    public String getCpuModel() {
        return cpuModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.cpu_model
     *
     * @param cpuModel the value for server.cpu_model
     *
     * @mbg.generated
     */
    public void setCpuModel(String cpuModel) {
        this.cpuModel = cpuModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.create_at
     *
     * @return the value of server.create_at
     *
     * @mbg.generated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.create_at
     *
     * @param createAt the value for server.create_at
     *
     * @mbg.generated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.last_online
     *
     * @return the value of server.last_online
     *
     * @mbg.generated
     */
    public Date getLastOnline() {
        return lastOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.last_online
     *
     * @param lastOnline the value for server.last_online
     *
     * @mbg.generated
     */
    public void setLastOnline(Date lastOnline) {
        this.lastOnline = lastOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.agent_address
     *
     * @return the value of server.agent_address
     *
     * @mbg.generated
     */
    public String getAgentAddress() {
        return agentAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.agent_address
     *
     * @param agentAddress the value for server.agent_address
     *
     * @mbg.generated
     */
    public void setAgentAddress(String agentAddress) {
        this.agentAddress = agentAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.ssh_address
     *
     * @return the value of server.ssh_address
     *
     * @mbg.generated
     */
    public String getSshAddress() {
        return sshAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.ssh_address
     *
     * @param sshAddress the value for server.ssh_address
     *
     * @mbg.generated
     */
    public void setSshAddress(String sshAddress) {
        this.sshAddress = sshAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.jmx_address
     *
     * @return the value of server.jmx_address
     *
     * @mbg.generated
     */
    public String getJmxAddress() {
        return jmxAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.jmx_address
     *
     * @param jmxAddress the value for server.jmx_address
     *
     * @mbg.generated
     */
    public void setJmxAddress(String jmxAddress) {
        this.jmxAddress = jmxAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.snmp_address
     *
     * @return the value of server.snmp_address
     *
     * @mbg.generated
     */
    public String getSnmpAddress() {
        return snmpAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.snmp_address
     *
     * @param snmpAddress the value for server.snmp_address
     *
     * @mbg.generated
     */
    public void setSnmpAddress(String snmpAddress) {
        this.snmpAddress = snmpAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.config_updated
     *
     * @return the value of server.config_updated
     *
     * @mbg.generated
     */
    public Boolean getConfigUpdated() {
        return configUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.config_updated
     *
     * @param configUpdated the value for server.config_updated
     *
     * @mbg.generated
     */
    public void setConfigUpdated(Boolean configUpdated) {
        this.configUpdated = configUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.asset_id
     *
     * @return the value of server.asset_id
     *
     * @mbg.generated
     */
    public Integer getAssetId() {
        return assetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.asset_id
     *
     * @param assetId the value for server.asset_id
     *
     * @mbg.generated
     */
    public void setAssetId(Integer assetId) {
        this.assetId = assetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column server.data_collector_id
     *
     * @return the value of server.data_collector_id
     *
     * @mbg.generated
     */
    public Integer getDataCollectorId() {
        return dataCollectorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column server.data_collector_id
     *
     * @param dataCollectorId the value for server.data_collector_id
     *
     * @mbg.generated
     */
    public void setDataCollectorId(Integer dataCollectorId) {
        this.dataCollectorId = dataCollectorId;
    }
}